version: '3'
services:
  opencart:
    build: .
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - .:/var/www/html
    command: /var/www/html/download.sh
    environment:
      XDEBUG_CONFIG: remote_host=172.30.143.22
    networks:
        - backend
  database:
    image: mysql:5.7
    command:
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
        - --innodb-strict-mode=OFF
        - --sql-mode=ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    environment:
        - "MYSQL_USER=${MYSQL_USER:-opencart}"
        - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}"
        - "MYSQL_DATABASE=${MYSQL_DATABASE:-opencart}"
        - "MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-password}"
    networks:
        - backend
    volumes:
    - ./data:/var/lib/mysql
    - ./db-import:/docker-entrypoint-initdb.d
volumes:
  database:
networks:
  backend: